main:
  - name: Home
    url: "/"
    weight: 10
  - name: About Us
    url: "/about/"
    weight: 20
  - name: Archive
    url: "/archive/"
    weight: 30
  - name: "2024"
    parent: Archive
    url: "/archive-2024/"
    weight: 10
  - name: "2025"
    parent: Archive
    url: "/archive-2025/"
    weight: 20

main_footer:
  # - name: Terms & Conditions
  #   url: "/terms-and-conditions/"
  #   weight: 10
  - name: Privacy Policy
    url: "/privacy-policy/"
    weight: 20
